# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'tscc' do
  pod 'ASIHTTPRequest', '~> 1.8.2'
  pod 'MBProgressHUD', '~> 0.9.1'

end

target 'tsccTests' do

end

